spring.application.name=stock-game
spring.datasource.url=jdbc:postgresql://localhost:5432/stock_game
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

stock.api.key=cu7id19r01qkucct2r5gcu7id19r01qkucct2r60
stock.api.url=https://finnhub.io/api/v1